8279077: JFR crashes on Linux ppc due to missing crash protector in signal handler
openjdk/jdk15u-dev pull request #155
Opened 2021-12-21 20:34 UTC by zhengyu123

This is a linux_ppc specific bug, probably a day-one bug till relevant code was refactored by JDK-8255711 in 16.

Linux ppc signal handler does not install crash protector as other Linux based platforms do, e.g. linux_x86, that can result a crash while jfr tries to fill stack trace for other thread.

2021-12-22 00:02 UTC, phohensee requested changes
Please add the jdk16 and later comment:

  // Handle JFR thread crash protection.
  //  Note: this may cause us to longjmp away. Do not use any code before this
  //  point which really needs any form of epilogue code running, eg RAII objects.

2021-12-22 13:30 UTC, zhengyu123 commented
> Please add the jdk16 and later comment:
> 
> // Handle JFR thread crash protection. // Note: this may cause us to longjmp away. Do not use any code before this // point which really needs any form of epilogue code running, eg RAII objects.

If we want to update comments, we should do it cross all relevant platforms. This is a linux ppc specific bug, would you mind to update comments in separate CR?

Thanks,

2021-12-22 19:59 UTC, phohensee approved these changes
Fine with me, though note that all releases from 16 on have the same comment.

2021-12-22 20:11 UTC, zhengyu123 commented
> Fine with me, though note that all releases from 16 on have the same comment.

Filed: JDK-8279181

2021-12-26 19:10 UTC, phohensee commented
Thanks you, Zhengyu.

2022-01-04 16:27 UTC, zhengyu123 commented
/integrate

2022-01-04 16:28 UTC, zhengyu123 commented
Got approval, integrated.

2022-01-04 16:29 UTC, closed without merging